version: '3'
services:
  amqp:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
#KAFKA
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    extra_hosts:
    - "moby:127.0.0.1"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka
    hostname: broker
    extra_hosts:
    - "moby:127.0.0.1"
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:9092'
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  schema_registry:
    image: confluentinc/cp-schema-registry
    hostname: schema_registry
    # extra_hosts:
    # - "moby:127.0.0.1"
    depends_on:
      - zookeeper
      - broker
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
  kafka-rest:
    image: confluentinc/cp-kafka-rest
    container_name: kafka-rest
    extra_hosts:
    - "moby:127.0.0.1"
    depends_on:
      - zookeeper
      - broker
      - schema_registry
    ports:
      - '8082:8082'
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_REST_LISTENERS: http://kafka-rest:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_REST_HOST_NAME: kafka-rest
#  db:
#    image: mongo:latest
#    container_name: mongodb
#    ports:
#      - "27018:27017"
#  index:
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
#    container_name: elasticsearch
#    environment:
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    ports:
#      - "9200:9200"
#  graph:
#    image: orientdb:latest
#    container_name: orientdb
#    ports:
#      - "2424:2424"
#      - "2480:2480"
#    environment:
#      ORIENTDB_ROOT_PASSWORD: 'admin'
#  cache:
#    image: redis:latest
#    container_name: redis
#    ports:
#      - "6379:6379"
  command:
    build: ./command
    environment:
      DB_URL: 'mongodb://db:27017'
      AMQP_URL: 'amqp://amqp:5672'
      KAFKA_URL: 'zookeeper:2181'
    ports:
      - "3000:3000"
    depends_on:
      - amqp
      - broker
#      - db
  query:
    build: ./query
    environment:
      DB_URL: 'mongodb://db:27017'
      AMQP_URL: 'amqp://amqp:5672'
      KAFKA_URL: 'zookeeper:2181'
    ports:
      - "3001:3001"
    depends_on:
      - amqp
      - broker
#      - db